#!/usr/bin/env bash
# setup-wg-vps.sh — WireGuard setup for the VPS (10.77.0.1)
#
# Run on the VPS as root. Two-pass:
#
#   Pass 1 — generate VPS keys, print VPS public key:
#     sudo bash /opt/hive/scripts/setup-wg-vps.sh
#
#   Pass 2 — add analysis machine public key, bring up tunnel:
#     sudo bash /opt/hive/scripts/setup-wg-vps.sh --peer <ANALYSIS_PUBKEY>
#
# WireGuard addresses:
#   VPS (this machine):      10.77.0.1/24  ListenPort 51820
#   Analysis machine:        10.77.0.2/32  (peer)

set -euo pipefail

WG_IF="wg0"
WG_DIR="/etc/wireguard"
PRIVKEY_FILE="$WG_DIR/vps.key"
PUBKEY_FILE="$WG_DIR/vps.pub"
CONF="$WG_DIR/$WG_IF.conf"

WG_VPS_ADDR="10.77.0.1/24"
WG_LISTEN_PORT="51820"
WG_ANALYSIS_ALLOWED="10.77.0.2/32"

green() { printf '\033[0;32m%s\033[0m\n' "$*"; }
info()  { printf '  \033[0;34m→\033[0m %s\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }

if [ "$(id -u)" -ne 0 ]; then
    echo "error: must run as root" >&2
    exit 1
fi

if ! command -v wg &>/dev/null; then
    info "installing wireguard..."
    apt-get update -qq
    apt-get install -y -qq wireguard
fi

mkdir -p "$WG_DIR"
chmod 700 "$WG_DIR"

if [ ! -f "$PRIVKEY_FILE" ]; then
    info "generating VPS keypair..."
    wg genkey | tee "$PRIVKEY_FILE" | wg pubkey > "$PUBKEY_FILE"
    chmod 600 "$PRIVKEY_FILE"
fi

VPS_PRIVKEY="$(cat "$PRIVKEY_FILE")"
VPS_PUBKEY="$(cat "$PUBKEY_FILE")"

if [ "${1:-}" != "--peer" ]; then
    info "writing partial wg0.conf (no peer yet)..."
    cat > "$CONF" <<EOF
# /etc/wireguard/wg0.conf — VPS side (10.77.0.1)
# Generated by setup-wg-vps.sh — do not edit manually.
# Re-run with --peer <ANALYSIS_PUBKEY> to complete setup.

[Interface]
Address    = $WG_VPS_ADDR
ListenPort = $WG_LISTEN_PORT
PrivateKey = $VPS_PRIVKEY
EOF
    chmod 600 "$CONF"

    echo ""
    bold "  ── VPS WireGuard: Pass 1 complete ──────────────────────────────────"
    echo ""
    echo "  VPS public key:"
    echo ""
    printf '    \033[1;33m%s\033[0m\n' "$VPS_PUBKEY"
    echo ""
    echo "  On your ANALYSIS MACHINE, run:"
    echo ""
    echo "    sudo bash hive/phase1/wireguard/setup-wg-analysis.sh --peer $VPS_PUBKEY"
    echo ""
    echo "  That script will print the ANALYSIS MACHINE public key."
    echo "  Then come back here and run:"
    echo ""
    echo "    sudo bash /opt/hive/scripts/setup-wg-vps.sh --peer <ANALYSIS_PUBKEY>"
    echo ""
    exit 0
fi

ANALYSIS_PUBKEY="${2:?'usage: setup-wg-vps.sh --peer <ANALYSIS_PUBKEY>'}"

info "writing final wg0.conf..."
cat > "$CONF" <<EOF
# /etc/wireguard/wg0.conf — VPS side (10.77.0.1)
# Generated by setup-wg-vps.sh

[Interface]
Address    = $WG_VPS_ADDR
ListenPort = $WG_LISTEN_PORT
PrivateKey = $VPS_PRIVKEY

[Peer]
# Analysis machine
PublicKey  = $ANALYSIS_PUBKEY
AllowedIPs = $WG_ANALYSIS_ALLOWED
EOF
chmod 600 "$CONF"

info "enabling and starting wg0..."
systemctl enable wg-quick@wg0
systemctl restart wg-quick@wg0

echo ""
green "  WireGuard tunnel up on VPS."
echo ""
echo "  Interface: $WG_IF  Address: $WG_VPS_ADDR  Port: $WG_LISTEN_PORT"
echo ""
echo "  Verify from analysis machine:"
echo "    ping 10.77.0.1"
echo ""
