#!/usr/bin/env bash
# setup-wg-analysis.sh — WireGuard setup for local (10.77.0.2)
#
# Run locally as root. Requires the VPS public key (from setup-wg-vps.sh pass 1).
#
# Usage:
#   sudo bash hive/phase1/wireguard/setup-wg-analysis.sh --peer <VPS_PUBKEY>
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../scripts/hive.conf"

WG_IF="wg0"
WG_DIR="/etc/wireguard"
PRIVKEY_FILE="$WG_DIR/analysis.key"
PUBKEY_FILE="$WG_DIR/analysis.pub"
CONF="$WG_DIR/$WG_IF.conf"

WG_ANALYSIS_ADDR="10.77.0.2/24"
VPS_PUBLIC_IP="$VPS_IP"
VPS_LISTEN_PORT="51820"
WG_VPS_ALLOWED="10.77.0.1/32"

green() { printf '\033[0;32m%s\033[0m\n' "$*"; }
info()  { printf '  \033[0;34m→\033[0m %s\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }

if [ "$(id -u)" -ne 0 ]; then
    echo "error: must run as root (sudo)" >&2
    exit 1
fi

if [ "${1:-}" != "--peer" ]; then
    echo "usage: sudo bash setup-wg-analysis.sh --peer <VPS_PUBKEY>" >&2
    echo ""
    echo "  Run setup-wg-vps.sh on the VPS first to get its public key." >&2
    exit 1
fi

VPS_PUBKEY="${2:?'--peer requires the VPS public key as the next argument'}"

if ! command -v wg &>/dev/null; then
    info "installing wireguard..."
    apt-get update -qq
    apt-get install -y -qq wireguard
fi

mkdir -p "$WG_DIR"
chmod 700 "$WG_DIR"

if [ ! -f "$PRIVKEY_FILE" ]; then
    info "generating analysis machine keypair..."
    wg genkey | tee "$PRIVKEY_FILE" | wg pubkey > "$PUBKEY_FILE"
    chmod 600 "$PRIVKEY_FILE"
fi

ANALYSIS_PRIVKEY="$(cat "$PRIVKEY_FILE")"
ANALYSIS_PUBKEY="$(cat "$PUBKEY_FILE")"

info "writing wg0.conf..."
cat > "$CONF" <<EOF
# /etc/wireguard/wg0.conf — analysis machine (10.77.0.2)
# Generated by setup-wg-analysis.sh

[Interface]
Address    = $WG_ANALYSIS_ADDR
PrivateKey = $ANALYSIS_PRIVKEY

[Peer]
# VPS hive
PublicKey  = $VPS_PUBKEY
Endpoint   = $VPS_PUBLIC_IP:$VPS_LISTEN_PORT
AllowedIPs = $WG_VPS_ALLOWED
# Keepalive so NAT doesn't drop the tunnel
PersistentKeepalive = 25
EOF
chmod 600 "$CONF"

info "enabling and starting wg0..."
systemctl enable wg-quick@wg0
systemctl restart wg-quick@wg0

echo ""
green "  WireGuard tunnel up on analysis machine."
echo ""
echo "  Interface: $WG_IF  Address: $WG_ANALYSIS_ADDR"
echo ""
bold "  ── Final step: add analysis key to VPS ─────────────────────────────"
echo ""
echo "  Analysis machine public key:"
echo ""
printf '    \033[1;33m%s\033[0m\n' "$ANALYSIS_PUBKEY"
echo ""
echo "  On the VPS, run:"
echo ""
echo "    sudo bash /opt/hive/scripts/setup-wg-vps.sh --peer $ANALYSIS_PUBKEY"
echo ""
echo "  Then verify the tunnel:"
echo "    ping 10.77.0.1   (from here)"
echo "    ping 10.77.0.2   (from VPS)"
echo ""
